### PR TITLE
correct rewriting semantics to handle rewriting any step in the path

### LINKED ISSUE #12: problem with semantics of rewrite_segment
This specification is broken for the case where we replace the last step in the path. What is the past-the-last step handle in this case? We should change it to be begin to end inclusive, and this would resolve the problem. I'll implement it that way on my end.

```c++
    /**                                                                                                                                                        
     * Delete a segment of a path and rewrite it as some other sequence of steps. Returns a pair                                                               
     * of step_handle_t's that indicate the range of the new segment in the path. The segment to                                                               
     * delete should be designated by the first and the past-the-last step handle.  If the step                                                                
     * that is returned by path_begin is deleted, path_begin will now return the first step from                                                               
     * the new segment or, in the case that the new segment is empty, segment_end.                                                                             
     */
    virtual std::pair<step_handle_t, step_handle_t> rewrite_segment(const step_handle_t& segment_begin,
                                                                    const step_handle_t& segment_end,
                                                                    const std::vector<handle_t>& new_segment) = 0;
```

### PR DESCRIPTION
**Pull request by ekg**
Will resolve #12

### CODE REVIEW

**Comment by jeizenga** [comment]
There are several changes in the path interface I don't like here. I think that adding better reverse iteration is a good idea, but I don't think this is the right design yet.

First, as far as I can tell `path_forward_end_iterator` is redundant with `path_end`.  We shouldn't need both. Unless you mean something different by "magic path end" value. That description should really be made clearer if we want it to be part of a specification.

Based on the previous semantics, it also looks to me like your implementation of `for_each_step_in_path` is incorrect. You have the step comparing to `path_end` in every iteration as the bail out condition. However, on the circular path, both the first iteration and the past-the-last iteration will be pointing to the same step. You also removed my logic for distinguishing these cases. How do you plan to do this now? Perhaps this is what you meant by "magic"? I need some additional details about how you plan to implement this, and we need to discuss whether your solution can be applied to the other 4 graph implementations.

I also think we're mixing up terminology in a way that could be confusing. This PR is referring to the same object as a step and an iterator. It is true that steps are conceptually similar to iterators, but I still think that consistent naming is important.

The method you've used to implement reverse iteration, as far as I can tell, is to introduce a concept of a "before-the-beginning" step in addition to "past-the-last". I think that's reasonable. But then we should also have a method to retrieve the last step, which this PR does not. I would also prefer if we maintained the STL-ish terminology and called these something like `path_rbegin` and `path_rend`.

Beyond the code changes, I think that as a matter of procedure it would be better if we could leave PRs unmerged for longer than this to allow for discussion. I'd say a minimum of one day to let people in different time zones take a look (especially since it's perfectly possible to develop against a branch of libhandlegraph, so waiting on discussion should never be blocking). HandleGraphs have sort of become the fundamental object for everything we're working on, and a lot of people's code depends on these changes. We also don't have any CI for this library, which makes some amount of code review even more important, imo.

**Comment by ekg** [comment]
I don't fully understand what the changes to the semantics which you made
resolve. We had working implementations with full path functionality
before. I don't think that we needed to do this to support circular paths.

Unfortunately, the changes are incompatible with my implementation, and
would require significant effort to match. The reason is that you have
changed the meaning of a step_handle_t to be a kind of mixed iterator and
node traversal. Usually, it is like the occurrence_handle_t, and refers to
an actual path step. But to know when we reach the end of a path, we have
to also consider it as an iterator that might point to a non-existent
entity that doesn't have any other representation in the data model outside
of the handle graph interface. I think that this is very tricky.

I do see that there is a benefit for allowing the get_next_step and
get_prev_step functions to never break. This is why it makes sense to
return these magic values for one-past the end and beginning of the path.
However, it is not a requirement to have this functionality. We previously
enforced the use of a check that we weren't at the end or beginning of the
path.

I have changed the meaning of path_begin and path_end to mean the first and
last steps in the path. As a result, this concern is not a problem:

> However, on the circular path, both the first iteration and the
past-the-last iteration will be pointing to the same step.

We only reach the path end when we hit the last step in the stored version
of the circular path. If the implementation is incorrect then I will fix
it.

I would have preferred more time to discuss the semantic changes which you
made. I was not available to do so until yesterday. In these commits, I
have undone the breaking changes and set things back as they were
previously, while still including the concepts and interface that you added.

In the future I'll be happy to give more time before merging. In this case,
I didn't want to get bogged down in exchanges over this because I need to
keep moving. I assume we can sync up going forward.

I can meege the changes I've made with the other implementations. It's not
my intention to break things or cause problems with this.

>

**Comment by jeizenga** [comment]
Ah, I think I misunderstood what you did with `path_end`, sorry about that. Is it doing what `get_last_occurrence` used to do? And then you replaced the current semantics for `path_end` with this `end_iterator`? I that's the case, I think your `for_each_step_in_path` is fine, my bad.

The changes to the semantics were mostly meant to address some of the inconvenience of programming against the old API. For example, you used to have to manually check whether paths were empty. Also the lack of a past-the-last concept meant that a for-loop usually had to handle either the first or last step outside the loop, which is clumsy. I think the new semantics improve on those aspects. In addition, we also discussed how the old API required you to dip into the data structure twice on every iteration: once to check whether the next step exists and then again to retrieve it. Now that burden is pushed into the `step_handle_t` equality operator, which I think will usually be faster. Admittedly though, adding circular paths does complicate things a bit. The discussion was mostly here if you want to review/revive any of it: https://github.com/vgteam/libhandlegraph/issues/3

In any case, I agree that we can figure out a way to include everything. Now that I think I understand your changes more, I think I mostly want to discuss naming and documentation. Previously, I liked that the terminology here mirrored the terminology in STL, which I think will be very intuitive for developers. I suggested using `rend`  and `rbegin` in a PR on Friday, but after thinking about it a while I'm not so keen on that solution either. In STL, reverse iterators sort of "know" that they are traveling backward, so that moving "forward" actually moves them in reverse. The `step_handle_t` doesn't have that (although it might be a good feature if it did).

But yeah, sorry for the additional development burden. Hope it isn't giving you too much trouble.

**Comment by ekg** [comment]
Sorry for my testy response earlier. I think you get where I'm coming from. I was mostly concerned about us making work that blocks progress on the paper on this.

That said, I totally agree with you that the interface, with all its checks for path emptiness, and next-step-havingness isn't ideal. Having slept on it some, I do think you are right to have done this, in the sense that it will probably make it easier to program against. On the other hand, we probably need to spend some time in the coming days fixing down the details.

As usual, this code-level exchange has resulted in me improving my work. I found another bug in the process of syncing up the libhandlegraph interface...

**Pull request merged**
