### PR TITLE
set a node id increment hint

### PR DESCRIPTION
**Pull request by ekg**
@jeizenga this is what I was talking about doing to make it so we can have a generic from-GFA loader algorithm that works on models (just odgi for now) that need to know the minimum node id in order to build an efficient in-memory model.

What do you think? Is there a better way to do this? I can also just hack this into odgi and we can give it custom loading code for our tests. That might be better.

### CODE REVIEW

**Comment by ekg** [comment]
This is basically the only thing blocking the libhandlegraph paper.

**Comment by jeizenga** [comment]
Wouldn't we want that in the MutableHandleGraph interface instead of HandleGraph?

**Comment by ekg** [comment]
Oh yes! Right.

**Comment by ekg** [comment]
Other than the change to mutablehandlegraph, are there any objections?

**Pull request merged**
